// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQelA6gVVzebBTNVFF257qTEwL7qSa1Rk',
    appId: '1:36225708648:web:f177f29f1dc8edc19941dd',
    messagingSenderId: '36225708648',
    projectId: 'gerenciador-de-senhas-58ed9',
    authDomain: 'gerenciador-de-senhas-58ed9.firebaseapp.com',
    storageBucket: 'gerenciador-de-senhas-58ed9.appspot.com',
    measurementId: 'G-P70KJKQM0D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8_1u5NGfA1rw7wVR15PXu9aKCep110F8',
    appId: '1:36225708648:android:c183a2edac30d3209941dd',
    messagingSenderId: '36225708648',
    projectId: 'gerenciador-de-senhas-58ed9',
    storageBucket: 'gerenciador-de-senhas-58ed9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCodfTMiORjz848UPagKhrGARiVo-NkU3U',
    appId: '1:36225708648:ios:ef18b09f83f3eede9941dd',
    messagingSenderId: '36225708648',
    projectId: 'gerenciador-de-senhas-58ed9',
    storageBucket: 'gerenciador-de-senhas-58ed9.appspot.com',
    iosClientId: '36225708648-ssdn88edq5ol66ap7jho3koq6ui2oiv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketGenerator',
  );
}
